name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run:  echo "Hello World!"
  echoing-dir-n-data:
    runs-on: ubuntu-20.04
    steps:
      - name: echo shi..
        run: |
          echo ls, $(date)